// Общий объект инлайн-стилей S (из токенов C). Используется во всех компонентах как S.*.
import { C } from './theme.js';

export const S = {
  root:{background:C.bg,color:C.text,minHeight:'100vh',fontFamily:"'Inter',sans-serif",padding:'20px 20px 40px',maxWidth:1040,margin:'0 auto'},
  header:{display:'flex',justifyContent:'space-between',alignItems:'flex-end',flexWrap:'wrap',gap:16,marginBottom:18,paddingBottom:16,borderBottom:`1px solid ${C.border}`},
  eyebrow:{fontFamily:"'JetBrains Mono',monospace",fontSize:11,letterSpacing:'.12em',color:C.dim,marginBottom:4},
  h1:{fontFamily:"'Space Grotesk',sans-serif",fontSize:24,fontWeight:700,textTransform:'capitalize'},
  h1compact:{fontFamily:"'Space Grotesk',sans-serif",fontSize:18,fontWeight:700,textTransform:'capitalize'},
  gauges:{display:'flex',gap:18,alignItems:'center',flexWrap:'wrap'},
  gauge:{display:'flex',alignItems:'center',gap:8},
  miniGauge:{display:'flex',alignItems:'center',gap:5},
  profileBtn:{background:C.panelAlt,border:`1px solid ${C.border}`,borderRadius:'50%',width:38,height:38,fontSize:18,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center'},
  profTile:{display:'flex',alignItems:'center',gap:10,background:C.panelAlt,border:`1px solid ${C.border}`,borderRadius:10,padding:'12px 14px'},
  gaugeVal:{fontFamily:"'JetBrains Mono',monospace",fontSize:15,fontWeight:700},
  gaugeLabel:{fontSize:10.5,color:C.dim},
  gaugeBarWrap:{width:64,height:4,background:C.panelAlt,borderRadius:2,marginTop:4,overflow:'hidden'},
  gaugeBarFill:{height:'100%',background:C.cyan},
  exportBtn:{background:C.panelAlt,border:`1px solid ${C.border}`,borderRadius:6,padding:'8px 12px',color:C.text,fontSize:12.5,cursor:'pointer'},
  nav:{display:'flex',gap:4,marginBottom:20,flexWrap:'wrap'},
  tabBtn:{background:'transparent',border:'none',cursor:'pointer',padding:'9px 14px',fontSize:13.5,fontWeight:500,borderRadius:'6px 6px 0 0'},
  panel:{background:C.panel,border:`1px solid ${C.border}`,borderRadius:10,padding:16,marginBottom:16},
  panelTitle:{fontFamily:"'Space Grotesk',sans-serif",fontSize:14,fontWeight:700,marginBottom:10},
  dimSpan:{color:C.dim,fontSize:12,fontWeight:400,marginLeft:6},
  inputRow:{display:'flex',gap:8,flexWrap:'wrap'},
  input:{flex:1,minWidth:100,background:C.panelAlt,border:`1px solid ${C.border}`,borderRadius:6,padding:'9px 10px',color:C.text,fontSize:13.5,outline:'none'},
  select:{background:C.panelAlt,border:`1px solid ${C.border}`,borderRadius:6,padding:'9px 10px',color:C.text,fontSize:13.5,outline:'none'},
  textarea:{width:'100%',background:C.panelAlt,border:`1px solid ${C.border}`,borderRadius:6,padding:10,color:C.text,fontSize:13.5,outline:'none',resize:'vertical'},
  iconBtnAmber:{background:C.amber,border:'none',borderRadius:6,width:36,height:36,display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer',color:'#1A1200',flexShrink:0,fontSize:16},
  counterBtn:{background:'transparent',border:'none',color:C.amber,width:36,height:36,fontSize:19,fontWeight:600,lineHeight:1,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center'},
  navArrow:{background:C.panelAlt,border:`1px solid ${C.border}`,borderRadius:6,width:28,height:28,color:C.text,cursor:'pointer'},
  taskRow:{display:'flex',alignItems:'center',gap:10,padding:'8px 6px',borderRadius:6},
  emptyState:{color:C.dim,fontSize:13,fontStyle:'italic',padding:'8px 2px'},
  grid2:{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(0,1fr)',gap:16},
  grid3:{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(0,1fr) minmax(0,1fr)',gap:16},
  statCard:{background:C.panel,border:`1px solid ${C.border}`,borderRadius:10,padding:14},
  statVal:{fontFamily:"'JetBrains Mono',monospace",fontSize:17,fontWeight:700},
  toastWrap:{position:'fixed',right:16,bottom:16,display:'flex',flexDirection:'column',gap:8,zIndex:60,maxWidth:'calc(100vw - 32px)'},
  toast:{display:'flex',alignItems:'center',gap:12,background:C.panelAlt,border:`1px solid ${C.amber}`,borderRadius:10,padding:'10px 14px',boxShadow:'0 8px 28px rgba(0,0,0,.45)',minWidth:230},
  levelUpOverlay:{position:'fixed',inset:0,zIndex:200,display:'flex',alignItems:'center',justifyContent:'center',background:'rgba(6,9,13,.72)',backdropFilter:'blur(3px)',overflow:'hidden',cursor:'pointer'},
  levelUpCard:{position:'relative',zIndex:2,textAlign:'center',background:C.panel,border:`1px solid ${C.amber}`,borderRadius:18,padding:'30px 42px',boxShadow:'0 20px 70px rgba(0,0,0,.6)'},
  // --- мобильная навигация ---
  bottomNav:{position:'fixed',left:0,right:0,bottom:0,display:'flex',background:C.panel,borderTop:`1px solid ${C.border}`,zIndex:40,padding:'6px 4px',paddingBottom:'max(6px, env(safe-area-inset-bottom))'},
  bottomItem:{flex:1,background:'none',border:'none',cursor:'pointer',display:'flex',flexDirection:'column',alignItems:'center',gap:3,padding:'4px 2px'},
  sheetOverlay:{position:'fixed',inset:0,background:'rgba(0,0,0,.5)',zIndex:50,display:'flex',alignItems:'flex-end'},
  sheet:{width:'100%',background:C.panel,borderTop:`1px solid ${C.border}`,borderRadius:'16px 16px 0 0',padding:'10px 16px calc(20px + env(safe-area-inset-bottom))',maxHeight:'82vh',overflowY:'auto'},
  sheetGrab:{width:40,height:4,background:C.border,borderRadius:2,margin:'4px auto 8px'},
  sheetSection:{fontSize:11,letterSpacing:'.1em',color:C.dim,textTransform:'uppercase',margin:'16px 0 8px'},
  sheetGrid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(72px,1fr))',gap:8},
  sheetTile:{background:C.panelAlt,border:`1px solid ${C.border}`,borderRadius:10,padding:'12px 6px',display:'flex',flexDirection:'column',alignItems:'center',gap:6,cursor:'pointer',color:C.text},
  sheetRow:{display:'block',width:'100%',textAlign:'left',background:C.panelAlt,border:`1px solid ${C.border}`,borderRadius:8,padding:'12px 14px',color:C.text,fontSize:13.5,cursor:'pointer'},
  sheetBtn:{background:C.panelAlt,border:`1px solid ${C.border}`,borderRadius:8,padding:'10px 14px',color:C.text,fontSize:13,cursor:'pointer',flex:1,minWidth:90},
  // --- модальное окно (редактор заметки и т.п.) ---
  modalOverlay:{position:'fixed',inset:0,background:'rgba(0,0,0,.6)',zIndex:100,display:'flex',alignItems:'center',justifyContent:'center',padding:16},
  modalCard:{width:'100%',maxWidth:560,maxHeight:'88vh',overflowY:'auto',background:C.panel,border:`1px solid ${C.border}`,borderRadius:14,padding:'18px 18px 22px',boxShadow:'0 20px 60px rgba(0,0,0,.55)'},
  // --- сегмент-переключатель (статус «Дел» и т.п.) ---
  seg:{display:'inline-flex',gap:4,background:C.panelAlt,border:`1px solid ${C.border}`,borderRadius:8,padding:3},
  segBtn:{border:'none',background:'transparent',cursor:'pointer',padding:'5px 10px',borderRadius:6,fontSize:12,fontWeight:600},
};
