// Общий объект инлайн-стилей S (из токенов C). Используется во всех компонентах как S.*.
// Редизайн «Тихий» (session 043): секции без рамок — их разделяет воздух и подпись секции;
// плашка с фоном (statCard/plate) — только у самостоятельного объекта. Ключи сохранены.
import { C } from './theme.js';

const FONT = "'Onest',system-ui,sans-serif";

export const S = {
  root:{background:C.bg,color:C.text,minHeight:'100vh',fontFamily:FONT,padding:'20px 20px 40px',maxWidth:1040,margin:'0 auto'},
  header:{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:12,marginBottom:16},
  eyebrow:{fontSize:12.5,color:C.dim,marginBottom:2},
  h1:{fontSize:26,fontWeight:700,letterSpacing:'-.02em',lineHeight:1.1},
  h1compact:{fontSize:24,fontWeight:700,letterSpacing:'-.02em',lineHeight:1.1},
  gauges:{display:'flex',gap:16,alignItems:'center',flexWrap:'wrap'},
  gauge:{display:'flex',alignItems:'center',gap:8},
  miniGauge:{display:'flex',alignItems:'center',gap:5,color:C.dim,fontSize:12.5,fontVariantNumeric:'tabular-nums'},
  profileBtn:{background:'transparent',border:'none',borderRadius:'50%',width:34,height:34,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',color:C.dim,flex:'none'},
  avatarBtn:{background:C.panel,border:`1px solid ${C.border}`,borderRadius:'50%',width:34,height:34,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',color:C.dim,flex:'none',fontSize:13,fontWeight:600},
  profTile:{display:'flex',alignItems:'center',gap:10,background:C.panelAlt,borderRadius:12,padding:'12px 14px'},
  gaugeVal:{fontSize:17,fontWeight:700,fontVariantNumeric:'tabular-nums'},
  gaugeLabel:{fontSize:11.5,color:C.dim},
  gaugeBarWrap:{width:'100%',height:4,background:C.bg,borderRadius:4,marginTop:5,overflow:'hidden'},
  gaugeBarFill:{height:'100%',background:C.amber,borderRadius:4},
  exportBtn:{background:C.panelAlt,border:`1px solid ${C.panelAlt}`,borderRadius:10,padding:'9px 14px',color:C.text,fontSize:13.5,fontWeight:600,cursor:'pointer',display:'inline-flex',alignItems:'center',justifyContent:'center',gap:6},
  btnPrimary:{background:C.amber,border:`1px solid ${C.amber}`,borderRadius:10,padding:'9px 14px',color:'#17130C',fontSize:13.5,fontWeight:600,cursor:'pointer',display:'inline-flex',alignItems:'center',justifyContent:'center',gap:6},
  btnGhost:{background:'transparent',border:`1px solid ${C.border}`,borderRadius:10,padding:'7px 12px',color:C.text,fontSize:12.5,fontWeight:600,cursor:'pointer',display:'inline-flex',alignItems:'center',justifyContent:'center',gap:6},
  // Широкий экран (этап 7): боковое меню + колонка контента.
  desk:{background:C.bg,color:C.text,minHeight:'100vh',fontFamily:FONT,display:'flex',alignItems:'flex-start'},
  deskMain:{flex:1,minWidth:0,maxWidth:1120,margin:'0 auto',padding:'24px 32px 48px'},
  nav:{display:'flex',gap:2,marginBottom:22,flexWrap:'wrap',borderBottom:`1px solid ${C.border}`},
  tabBtn:{background:'transparent',border:'none',cursor:'pointer',padding:'10px 12px',fontSize:13.5,fontWeight:500,borderRadius:'8px 8px 0 0',display:'inline-flex',alignItems:'center',gap:7},
  panel:{background:'transparent',border:'none',borderRadius:0,padding:'0 0 4px',marginBottom:26},
  panelTitle:{fontSize:11.5,fontWeight:600,color:C.dim,letterSpacing:'.05em',textTransform:'uppercase',marginBottom:10},
  plate:{background:C.panel,borderRadius:12,padding:'12px 14px'},
  dimSpan:{color:C.dim,fontSize:12,fontWeight:500,marginLeft:6,letterSpacing:0,textTransform:'none'},
  inputRow:{display:'flex',gap:8,flexWrap:'wrap'},
  input:{flex:1,minWidth:0,background:C.panel,border:`1px solid ${C.border}`,borderRadius:10,padding:'10px 12px',color:C.text,fontSize:14,outline:'none'},
  select:{background:C.panel,border:`1px solid ${C.border}`,borderRadius:10,padding:'10px 12px',color:C.text,fontSize:14,outline:'none'},
  textarea:{width:'100%',background:C.panel,border:`1px solid ${C.border}`,borderRadius:12,padding:'12px 14px',color:C.text,fontSize:14,lineHeight:1.5,outline:'none',resize:'vertical'},
  iconBtnAmber:{background:C.amber,border:'none',borderRadius:10,width:40,height:40,display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer',color:'#17130C',flexShrink:0,fontSize:16},
  counterBtn:{background:C.panelAlt,border:'none',borderRadius:9,color:C.text,width:32,height:32,fontSize:17,fontWeight:500,lineHeight:1,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center'},
  navArrow:{background:'transparent',border:'none',borderRadius:8,width:32,height:32,color:C.dim,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center'},
  taskRow:{display:'flex',alignItems:'center',gap:12,padding:'11px 0',borderBottom:`1px solid ${C.border}`},
  emptyState:{color:C.dim,fontSize:13.5,padding:'10px 0'},
  grid2:{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(0,1fr)',gap:'0 32px'},
  grid3:{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(0,1fr) minmax(0,1fr)',gap:12},
  statCard:{background:C.panel,border:'none',borderRadius:12,padding:'12px 14px'},
  statVal:{fontSize:19,fontWeight:700,fontVariantNumeric:'tabular-nums'},
  toastWrap:{position:'fixed',right:16,bottom:16,display:'flex',flexDirection:'column',gap:8,zIndex:60,maxWidth:'calc(100vw - 32px)'},
  toast:{display:'flex',alignItems:'center',gap:12,background:'#26282D',border:'none',borderRadius:12,padding:'11px 14px',boxShadow:'0 10px 30px rgba(0,0,0,.45)',minWidth:230},
  levelUpOverlay:{position:'fixed',inset:0,zIndex:200,display:'flex',alignItems:'center',justifyContent:'center',background:'rgba(5,6,7,.66)',overflow:'hidden',cursor:'pointer',padding:24},
  levelUpCard:{position:'relative',zIndex:2,textAlign:'center',background:C.panel,border:'none',borderRadius:20,padding:'26px 28px 22px',boxShadow:'0 20px 50px rgba(0,0,0,.55)',minWidth:260},
  // --- мобильная навигация ---
  bottomNav:{position:'fixed',left:0,right:0,bottom:0,display:'flex',background:C.bg,borderTop:`1px solid ${C.border}`,zIndex:40,padding:'7px 4px',paddingBottom:'max(9px, env(safe-area-inset-bottom))'},
  bottomItem:{flex:1,background:'none',border:'none',cursor:'pointer',display:'flex',flexDirection:'column',alignItems:'center',gap:4,padding:'3px 2px',fontFamily:FONT},
  sheetOverlay:{position:'fixed',inset:0,background:'rgba(5,6,7,.62)',zIndex:50,display:'flex',alignItems:'flex-end'},
  sheet:{width:'100%',background:C.panel,borderRadius:'20px 20px 0 0',padding:'10px 18px calc(20px + env(safe-area-inset-bottom))',maxHeight:'86vh',overflowY:'auto',boxShadow:'0 -10px 30px rgba(0,0,0,.4)'},
  sheetGrab:{width:36,height:4,background:C.faint,borderRadius:4,margin:'2px auto 10px'},
  sheetSection:{fontSize:11.5,fontWeight:600,letterSpacing:'.05em',color:C.dim,textTransform:'uppercase',margin:'18px 0 8px'},
  sheetGrid:{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:8},
  sheetTile:{background:C.panelAlt,border:`1px solid ${C.panelAlt}`,borderRadius:12,padding:'14px 6px',display:'flex',flexDirection:'column',alignItems:'center',gap:7,cursor:'pointer',color:C.text,fontFamily:FONT},
  sheetRow:{display:'flex',alignItems:'center',gap:10,width:'100%',textAlign:'left',background:C.panelAlt,border:`1px solid ${C.panelAlt}`,borderRadius:12,padding:'12px 14px',color:C.text,fontSize:14,cursor:'pointer',marginBottom:6,fontFamily:FONT},
  sheetBtn:{background:C.panelAlt,border:`1px solid ${C.panelAlt}`,borderRadius:10,padding:'10px 14px',color:C.text,fontSize:13.5,fontWeight:600,cursor:'pointer',flex:1,minWidth:90,display:'inline-flex',alignItems:'center',justifyContent:'center',gap:6,fontFamily:FONT},
  // --- модальное окно ---
  modalOverlay:{position:'fixed',inset:0,background:'rgba(5,6,7,.62)',zIndex:100,display:'flex',alignItems:'center',justifyContent:'center',padding:16},
  modalCard:{width:'100%',maxWidth:560,maxHeight:'88vh',overflowY:'auto',background:C.panel,border:'none',borderRadius:16,padding:'18px 18px 22px',boxShadow:'0 20px 50px rgba(0,0,0,.5)'},
  // --- сегмент-переключатель ---
  seg:{display:'inline-flex',gap:2,background:C.panel,border:'none',borderRadius:10,padding:3},
  segBtn:{border:'none',background:'transparent',cursor:'pointer',padding:'6px 10px',borderRadius:8,fontSize:12.5,fontWeight:600,fontFamily:FONT},
};
